/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.mediaproxy.interfaces;

/**
 * Home interface for MediaProxyImpl.
 */
public interface MediaProxyImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MediaProxyImpl";
   public static final String JNDI_NAME="multimonster/mediaproxy/MediaProxyFacade";

   public multimonster.mediaproxy.interfaces.MediaProxyImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
