/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.mediaproxy.interfaces;

/**
 * Remote interface for MediaProxyImpl.
 */
public interface MediaProxyImpl
   extends javax.ejb.EJBObject
{

   public multimonster.common.ConnectionAddress getOutputProxy( multimonster.common.Session session,multimonster.common.media.MOIdentifier mOId,multimonster.common.FormatId fId,multimonster.common.ProtocolId protocolId )
      throws multimonster.mediaproxy.exceptions.MediaProxyException, java.rmi.RemoteException;

   public multimonster.common.ConnectionAddress getInputProxy( multimonster.common.Session session,multimonster.common.media.MOIdentifier mOId,multimonster.common.ProtocolId protocolId )
      throws multimonster.mediaproxy.exceptions.MediaProxyException, java.rmi.RemoteException;

   public multimonster.mediaproxy.ProxyInitObjects initWork( multimonster.common.Session session,multimonster.common.media.MOIdentifier mOId,multimonster.common.FormatId fId,multimonster.common.ProtocolId protocolId,multimonster.common.Action action,boolean isInput )
      throws multimonster.mediaproxy.exceptions.MediaProxyException, java.rmi.RemoteException;

   public void requestFinished( multimonster.common.resource.ResourceRequestIdentifier rrId )
      throws multimonster.mediaproxy.exceptions.MediaProxyException, java.rmi.RemoteException;

   public void directInput( byte[] file,java.lang.String link )
      throws java.rmi.RemoteException;

}
