/* Generated by Together */

package multimonster.systemadministration;

import org.apache.log4j.Logger;

import multimonster.common.edit.FilterAction;
import multimonster.common.media.MOIdentifier;
import multimonster.common.resource.Costs;

public class CostCalculator {
	
	private Logger log;
	
	public CostCalculator() {
		log = Logger.getLogger(this.getClass());
	}
	
    public Costs calculateCosts(MOIdentifier id, FilterAction[] actions) {
		log.debug("calculateCosts()");
		return new Costs();
    }

    public void realCosts(MOIdentifier id, FilterAction[] actions, Costs realcosts) {
		log.debug("realCosts()");
    }
}
