/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.usermanager.interfaces;

/**
 * Remote interface for UserManagerImpl.
 * @author Marc Iseler
 */
public interface UserManagerImpl
   extends javax.ejb.EJBObject
{

   public boolean checkUserAuth( multimonster.common.AuthData authData )
      throws java.rmi.RemoteException;

   public void logout( multimonster.common.UserIdentifier uid )
      throws java.rmi.RemoteException;

   public void createUser( multimonster.common.UserIdentifier UserID,java.lang.Object sharedSecret )
      throws java.rmi.RemoteException;

   public boolean remUser( multimonster.common.UserIdentifier UserID )
      throws java.rmi.RemoteException;

   public int createUsergroup(  )
      throws java.rmi.RemoteException;

   public void remUsergroup( int groupID )
      throws java.rmi.RemoteException;

   public void addUserToGroup( multimonster.common.UserIdentifier user,int group )
      throws java.rmi.RemoteException;

   public void remUserFromGroup( multimonster.common.UserIdentifier user,int group )
      throws java.rmi.RemoteException;

   public multimonster.common.UserGroup[] getAllUsergroups(  )
      throws java.rmi.RemoteException;

   public multimonster.common.User[] allUserInGroup( int groupID )
      throws java.rmi.RemoteException;

   public boolean isUserInGroup( multimonster.common.UserIdentifier user,int group )
      throws java.rmi.RemoteException;

   public void changeUser( multimonster.common.User user )
      throws java.rmi.RemoteException;

   public boolean login( multimonster.common.AuthData authData )
      throws java.rmi.RemoteException;

   public boolean isActionAllowed( multimonster.common.UserIdentifier user,multimonster.common.media.MOIdentifier mediaObject,multimonster.common.Action action )
      throws java.rmi.RemoteException;

   public void grantRight( int usergroup,multimonster.common.media.MOGroup mediaObjectGroup,multimonster.common.Action action )
      throws java.rmi.RemoteException;

   public void revokeRight( int usergroup,multimonster.common.media.MOGroup moGroup,multimonster.common.Action newAction )
      throws java.rmi.RemoteException;

}
