/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.usermanager.interfaces;

/**
 * Home interface for UserManagerImpl.
 * @author Marc Iseler
 */
public interface UserManagerImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserManagerImpl";
   public static final String JNDI_NAME="multimonster/edit/UserManagerFacade";

   public multimonster.usermanager.interfaces.UserManagerImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
