/* Generated by Together */

package multimonster.common;

import java.io.Serializable;

/**
 * Provides a flexible way to specify administrative commands
 * without the need to extend an interface for every new operation.<br>
 * An AdminOperation is identified by an operationID. <p>
 * 
 * Used as container to submit administrative operation command. 
 * Executer needs to "know" what to do when he get e.g. adminOpID = 2. 
 */
public class AdminOperation implements Serializable {

	private int adminOpID;
    private String adminOpName;
    private String description;

    //list of known commands:
    public final static int SHUTDOWN_SERVER = 1;
	
	public AdminOperation(int opID, String opName) {
		this.adminOpID = opID;
		this.adminOpName = opName;
    }

    public int getOperationID() {
		return adminOpID;
    } 

    public String getOperationName() {
		return adminOpName;
    }

    public String getDescription(){ 
    	return description; 
    }

    public void setdescription(String description){
    	this.description = description;
    }

}
