/* Generated by Together */

package multimonster.common;

import java.io.Serializable;

import multimonster.common.media.*;

/**
 * Specifies the format of a mediainstance.
 * It includes the information about the codec the structure. 
 * 
 * @author Holger Velke (sihovelk)
 */
public class Format implements Serializable{
    private FormatId formatId = null;
    private String description = "";
    private int resolutionVertical = 0;
    private int resolutionHorizontal = 0;
    private String aspectRatio = "";
    private int bandwidthMax = 0;
    private int bandwidthAvg = 0;
    private int bandwidthMin = 0;
    private int colorDepth = 0;
    private Colorspace colorSpace = null;
    private Codec codec = null;
    private Structure structure = null;
    private int bitrate = 0;
    private int fps = 0;    


	public Format(FormatId id) {
		this.formatId = id;
	}

	/**
	 * @return
	 */
	public int getBandwidthAvg() {
		return bandwidthAvg;
	}

	/**
	 * @return
	 */
	public int getBandwidthMax() {
		return bandwidthMax;
	}

	/**
	 * @return
	 */
	public int getBandwidthMin() {
		return bandwidthMin;
	}

	/**
	 * @return
	 */
	public Codec getCodec() {
		return codec;
	}

	/**
	 * @return
	 */
	public int getColorDepth() {
		return colorDepth;
	}

	/**
	 * @return
	 */
	public Colorspace getColorSpace() {
		return colorSpace;
	}

	/**
	 * @return
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @return
	 */
	public int getResolutionHorizontal() {
		return resolutionHorizontal;
	}

	/**
	 * @return
	 */
	public int getResolutionVertical() {
		return resolutionVertical;
	}

	/**
	 * @param i
	 */
	public void setBandwidthAvg(int i) {
		bandwidthAvg = i;
	}

	/**
	 * @param i
	 */
	public void setBandwidthMax(int i) {
		bandwidthMax = i;
	}

	/**
	 * @param i
	 */
	public void setBandwidthMin(int i) {
		bandwidthMin = i;
	}

	/**
	 * @param codec
	 */
	public void setCodec(Codec codec) {
		this.codec = codec;
	}

	/**
	 * @param i
	 */
	public void setColorDepth(int i) {
		colorDepth = i;
	}

	/**
	 * @param colorspace
	 */
	public void setColorSpace(Colorspace colorspace) {
		colorSpace = colorspace;
	}

	/**
	 * @param string
	 */
	public void setDescription(String string) {
		description = string;
	}

	/**
	 * @param i
	 */
	public void setResolutionHorizontal(int i) {
		resolutionHorizontal = i;
	}

	/**
	 * @param i
	 */
	public void setResolutionVertical(int i) {
		resolutionVertical = i;
	}

	/**
	 * @return
	 */
	public FormatId getFormatId() {
		return formatId;
	}

	/**
	 * @return Returns the bitrate.
	 */
	public int getBitrate() {
		return bitrate;
	}

	/**
	 * @param bitrate The bitrate to set.
	 */
	public void setBitrate(int bitrate) {
		this.bitrate = bitrate;
	}

	/**
	 * @return Returns the fps.
	 */
	public int getFps() {
		return fps;
	}

	/**
	 * @param fps The fps to set.
	 */
	public void setFps(int fps) {
		this.fps = fps;
	}

	/**
	 * @return Returns the aspectRatio.
	 */
	public String getAspectRatio() {
		return aspectRatio;
	}

	/**
	 * @param aspectRatio The aspectRatio to set.
	 */
	public void setAspectRatio(String aspectRatio) {
		this.aspectRatio = aspectRatio;
	}

	/**
	 * @return Returns the structure.
	 */
	public Structure getStructure() {
		return structure;
	}
	/**
	 * @param structure The structure to set.
	 */
	public void setStructure(Structure structure) {
		this.structure = structure;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	public String toString() {

		return "codec="+codec.toString()+" structure="+structure.toString();
	}

}
