/* Generated by Together */


package multimonster.common;


public class Proxy {
    private int id;
    private String name;
    private String description;
    private Protocol protocol;
    private ConnectionAddress connectionAddress;
}
