/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.mediaaccess.interfaces;

/**
 * Home interface for MediaAccessImpl.
 * @author Marc Iseler
 */
public interface MediaAccessImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MediaAccessImpl";
   public static final String JNDI_NAME="multimonster/mediaaccess/MediaAccessFacade";

   public multimonster.mediaaccess.interfaces.MediaAccessImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
