/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.mediaaccess.interfaces;

/**
 * Remote interface for MediaAccessImpl.
 * @author Marc Iseler
 */
public interface MediaAccessImpl
   extends javax.ejb.EJBObject
{

   public multimonster.common.media.MIIdentifier newMediaInstanceData( multimonster.common.pipe.Pipe inputPipe )
      throws java.rmi.RemoteException;

   public multimonster.common.pipe.Pipe getMediaInstanceData( multimonster.common.media.MIIdentifier mIId )
      throws java.rmi.RemoteException;

   public boolean remMediaInstance( multimonster.common.media.MIIdentifier p0 )
      throws java.rmi.RemoteException;

}
