/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.resourcemanager.interfaces;

/**
 * Remote interface for ResourceManagerImpl.
 * @see multimonster.resourcemanager.ResourceManagerFacade
 * @author Holger Velke (sihovelk)
 */
public interface ResourceManagerImpl
   extends javax.ejb.EJBObject
{

   public multimonster.common.resource.ResourceRequestIdentifier requestResources( multimonster.common.UserIdentifier uId,multimonster.common.resource.Costs costs,multimonster.common.resource.QueueTime maxQT,multimonster.common.resource.ResourceWaiter waiter )
      throws multimonster.resourcemanager.exceptions.ResourceManagerException, java.rmi.RemoteException;

   public multimonster.common.resource.ResourceRequestIdentifier requestResources( multimonster.common.UserIdentifier uId,multimonster.common.resource.Costs costs )
      throws multimonster.resourcemanager.exceptions.ResourceManagerException, java.rmi.RemoteException;

   public multimonster.common.resource.Costs releaseResources( multimonster.common.resource.ResourceRequestIdentifier rrId )
      throws multimonster.resourcemanager.exceptions.ResourceManagerException, java.rmi.RemoteException;

}
