/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.converter.interfaces;

/**
 * Remote interface for ConverterImpl.
 * @author Holger Velke
 */
public interface ConverterImpl
   extends javax.ejb.EJBObject
{

   public multimonster.common.pipe.Pipe getMediaInstance( multimonster.common.media.MOIdentifier mOId,multimonster.common.FormatId fId )
      throws multimonster.converter.exceptions.ConverterException, java.rmi.RemoteException;

   public multimonster.common.pipe.Pipe getSourceMediaInstance( multimonster.common.media.MOIdentifier mOId )
      throws multimonster.converter.exceptions.ConverterException, java.rmi.RemoteException;

   public void addMediaObject( multimonster.common.media.MOIdentifier mOId,multimonster.common.pipe.Pipe input )
      throws multimonster.converter.exceptions.ConverterException, java.rmi.RemoteException;

   public boolean removeMediaInstance( multimonster.common.media.MIIdentifier mIId )
      throws multimonster.converter.exceptions.ConverterException, java.rmi.RemoteException;

}
