/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.converter.interfaces;

/**
 * Home interface for ConverterImpl.
 * @author Holger Velke
 */
public interface ConverterImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ConverterImpl";
   public static final String JNDI_NAME="multimonster/converter/ConverterFacade";

   public multimonster.converter.interfaces.ConverterImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
