/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.transporter.interfaces;

/**
 * Remote interface for TransporterImpl.
 * @author Jörg Meier
 */
public interface TransporterImpl
   extends javax.ejb.EJBObject
{

   public multimonster.common.pipe.Pipe output( multimonster.common.media.MOIdentifier mOId,multimonster.common.FormatId fId,multimonster.common.ProtocolId protocolId )
      throws multimonster.transporter.exceptions.TransporterException, java.rmi.RemoteException;

   public multimonster.common.pipe.Pipe input( multimonster.common.media.MOIdentifier mOId,multimonster.common.ProtocolId protocolId )
      throws multimonster.transporter.exceptions.TransporterException, java.rmi.RemoteException;

   public boolean registerProxy( multimonster.common.Proxy proxy )
      throws java.rmi.RemoteException;

   public boolean releaseProxy( multimonster.common.Proxy proxy )
      throws java.rmi.RemoteException;

   public void changeSetting( multimonster.common.setting.Setting[] setting )
      throws java.rmi.RemoteException;

   public void addPlugIn( multimonster.common.plugin.PlugInInformation plugInInformation )
      throws java.rmi.RemoteException;

   public void releasePlugIn( multimonster.common.plugin.PlugInIdentifier plugInId )
      throws java.rmi.RemoteException;

   public void removePlugIn( multimonster.common.plugin.PlugInIdentifier plugInId )
      throws java.rmi.RemoteException;

}
