/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.systemadministration.interfaces;

/**
 * Home interface for SystemAdministrationImpl.
 */
public interface SystemAdministrationImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SystemAdministrationImpl";
   public static final String JNDI_NAME="multimonster/systemadministration/SystemAdministrationFacade";

   public multimonster.systemadministration.interfaces.SystemAdministrationImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException,java.rmi.RemoteException;

}
