/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.controller.interfaces;

/**
 * Remote interface for ControllerImpl.
 * @author Jörg Meier
 */
public interface ControllerImpl
   extends javax.ejb.EJBObject
{

   public boolean login( multimonster.common.AuthData auth )
      throws multimonster.controller.exceptions.ControllerException, multimonster.controller.exceptions.InvalidAuthDataException, java.rmi.RemoteException;

   public void logout(  )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public boolean authorize( multimonster.common.Session s,multimonster.common.media.MOIdentifier mo,multimonster.common.Action action )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.InputOption[] getInputOptions(  )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.OutputOption[] getOutputOptions( multimonster.common.media.MOIdentifier mOId )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.ConnectionAddress prepareInsert( multimonster.common.ProtocolId protocolId,multimonster.common.media.MetaData metaData )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.ConnectionAddress prepareOutput( multimonster.common.media.MOIdentifier mOId,multimonster.common.OutputOption oo )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public void setMetaData( multimonster.common.media.MediaObject mo )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.media.MetaDataAccess getMetaData( multimonster.common.media.MOIdentifier mOId )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public boolean deleteMediaObject( multimonster.common.media.MOIdentifier mOId )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.SearchResult[] search( multimonster.common.SearchCriteria search )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.AdminResult administration( multimonster.common.AdminOperation operation )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.edit.FilterDetail[] getFilterOptions( multimonster.common.media.MOIdentifier mOId )
      throws java.rmi.RemoteException;

   public multimonster.common.edit.EditJobIdentifier getEditJob( multimonster.common.media.MOIdentifier mo )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public multimonster.common.media.MediaObject finishEditJob( multimonster.common.edit.EditJobIdentifier job,multimonster.common.media.MetaData metaData,multimonster.common.resource.QueueTime maxQT )
      throws java.rmi.RemoteException;

   public multimonster.common.edit.EditJobIdentifier[] getEditJobList(  )
      throws java.rmi.RemoteException;

   public multimonster.common.edit.EditTaskIdentifier addTaskToEditJob( multimonster.common.edit.EditJobIdentifier jobId,multimonster.common.edit.FilterPlugInIdentifier filterId,multimonster.common.edit.FilterAction action )
      throws java.rmi.RemoteException;

   public void removeEditTask( multimonster.common.edit.EditJobIdentifier job,multimonster.common.edit.EditTaskIdentifier task )
      throws java.rmi.RemoteException;

   public void abortEditJob( multimonster.common.edit.EditJobIdentifier job )
      throws java.rmi.RemoteException;

   public multimonster.common.resource.ResourceRequestIdentifier requestResources( multimonster.common.Session s,multimonster.common.media.MOIdentifier moid,multimonster.common.FormatId fId,multimonster.common.ProtocolId protocolId,multimonster.common.Action action )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

   public void releaseResource( multimonster.common.resource.ResourceRequestIdentifier rrId )
      throws multimonster.controller.exceptions.ControllerException, java.rmi.RemoteException;

}
