/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.controller.interfaces;

/**
 * Home interface for ControllerImpl.
 * @author Jörg Meier
 */
public interface ControllerImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ControllerImpl";
   public static final String JNDI_NAME="multimonster/controller/ControllerFacade";

   public multimonster.controller.interfaces.ControllerImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
