/*
 * Generated file - Do not edit!
 */
package multimonster.converter.plugin.jmx;

/**
 * MBean interface.
 * @author XDoclet (autogenerated)
 */
public interface TCProbeCallerMBean extends org.jboss.system.ServiceMBean {

  java.lang.String getTCPROBE_ARGS() ;

  void setTCPROBE_ARGS(java.lang.String tcprobe_args) ;

  java.lang.String getTCPROBE_PATH() ;

  void setTCPROBE_PATH(java.lang.String tcprobe_path) ;

   /**
    * this can only be used within the same VM.
    */
  multimonster.converter.plugin.jmx.TCProbeCaller returnThis() ;

}
