/* Generated by Together */

package multimonster.common.setting;

import java.io.Serializable;

public class SettingValue implements Serializable {
	static final long serialVersionUID = 2034850;
	
    private boolean continuous;
    private Comparable valueCont;
    private Object valueDiscr;
    
    public SettingValue(int value) {
    	this.valueCont = new Integer(value);
    	this.continuous = true;
    }
	/**
	 * @return
	 */
	public boolean isContinuous() {
		return continuous;
	}

	/**
	 * @return
	 */
	public Comparable getValueCont() {
		return valueCont;
	}

	/**
	 * @return
	 */
	public Object getValueDiscr() {
		return valueDiscr;
	}

	/**
	 * @param b
	 */
	public void setContinuous(boolean b) {
		continuous = b;
	}

	/**
	 * @param comparable
	 */
	public void setValueCont(Comparable comparable) {
		valueCont = comparable;
	}

	/**
	 * @param object
	 */
	public void setValueDiscr(Object object) {
		valueDiscr = object;
	}

}
