/* Generated by Together */

package multimonster.common.setting;

import java.io.Serializable;

public class Setting implements Serializable{
	
    private SettingID id;
    private String name;
    private SettingValue value;
    private SettingDomain domain;
    private String description;
	
    /**
	 * @param name
	 * @param value
	 * @param domain
	 * @param description
	 */
	public Setting(String name, SettingValue value, SettingDomain domain,
			String description) {
		super();
		this.name = name;
		this.value = value;
		this.domain = domain;
		this.description = description;
	}
    
    /**
	 * @return
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @return
	 */
	public SettingDomain getDomain() {
		return domain;
	}

	/**
	 * @return
	 */
	public SettingID getId() {
		return id;
	}

	/**
	 * @return
	 */
	public String getName() {
		return name;
	}

	/**
	 * @return
	 */
	public SettingValue getValue() {
		return value;
	}

	/**
	 * @param string
	 */
	public void setDescription(String string) {
		description = string;
	}

	/**
	 * @param domain
	 */
	public void setDomain(SettingDomain domain) {
		this.domain = domain;
	}

	/**
	 * @param settingID
	 */
	public void setId(SettingID settingID) {
		id = settingID;
	}

	/**
	 * @param string
	 */
	public void setName(String string) {
		name = string;
	}

	/**
	 * @param value
	 */
	public void setValue(SettingValue value) {
		this.value = value;
	}

}
