/* Generated by Together */

package multimonster.common.setting;

/**
 * runs in every component and serves as local proxy for settings which are administrated by the administrator of the system.
 * this proxy was set up, because settings are much more often read, than they are changed. 
 */
public class SettingManager {
    /**
     * Wird von Fassade aufgerufen, wenn diese ein 'settingChange' erhält. 
     */
    public void changeSetting(Setting[] settings) {
	} 



    void newSetting(Setting[] settings) {
	}

    void removeSetting(Setting[] settings) {
	}

    SettingValue getSetting(String name) {
		return null;
	}

    private Setting[] settings;
}
