/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.edit.interfaces;

/**
 * Remote interface for EditImpl.
 * @see multimonster.edit.EditFacade
 * @author Holger Velke (sihovelk)
 */
public interface EditImpl
   extends javax.ejb.EJBObject
{

   public multimonster.common.edit.EditJobIdentifier getJob( multimonster.common.UserIdentifier uId,multimonster.common.media.MOIdentifier mOId )
      throws multimonster.edit.exceptions.EditException, java.rmi.RemoteException;

   public multimonster.common.edit.EditTaskIdentifier addTaskToJob( multimonster.common.edit.EditJobIdentifier jobId,multimonster.common.edit.FilterPlugInIdentifier filterId,multimonster.common.edit.FilterAction action )
      throws multimonster.edit.exceptions.EditException, java.rmi.RemoteException;

   public multimonster.common.media.MOIdentifier finishJob( multimonster.common.edit.EditJobIdentifier jobId,multimonster.common.media.MetaData metaData,multimonster.common.resource.QueueTime maxQT )
      throws multimonster.edit.exceptions.EditException, java.rmi.RemoteException;

   public void removeTask( multimonster.common.edit.EditTaskIdentifier taskId )
      throws multimonster.edit.exceptions.EditException, java.rmi.RemoteException;

   public void abortJob( multimonster.common.edit.EditJobIdentifier jobId )
      throws multimonster.edit.exceptions.EditException, java.rmi.RemoteException;

   public multimonster.common.edit.EditJobIdentifier[] getJobList( multimonster.common.UserIdentifier uId )
      throws multimonster.edit.exceptions.EditException, java.rmi.RemoteException;

   public void grantResource( multimonster.common.resource.ResourceRequestIdentifier rrId )
      throws java.rmi.RemoteException;

   public void denyResource( multimonster.common.resource.ResourceRequestIdentifier rrId )
      throws java.rmi.RemoteException;

}
