/*
 * Generated by XDoclet - Do not edit!
 */
package multimonster.edit.interfaces;

/**
 * Home interface for EditImpl.
 * @see multimonster.edit.EditFacade
 * @author Holger Velke (sihovelk)
 */
public interface EditImplHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EditImpl";
   public static final String JNDI_NAME="multimonster/edit/EditFacade";

   public multimonster.edit.interfaces.EditImpl create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
