/* Generated by Together */

package multimonster.common.media;

import java.io.Serializable;
import java.util.Date;

public class Actor  implements Serializable{
    private String name;
    private Date dateOfBirth; 
    private String nativeCountry;
}
