/* Generated by Together */

package multimonster.common.media;

import java.io.Serializable;

public class Colorspace  implements Serializable{
    private int colorSpaceID;
    private String colorSpaceName;
}
