/* Generated by Together */

package multimonster.common.media;

import multimonster.common.Format;

/**
 * concrete Media-File with fixed format and a defined location. 
 */
public class MediaInstance {
	
	// by Holger
    /**
	 * @param mIId
	 * @param mOId
	 * @param format
	 */
	public MediaInstance(MIIdentifier mIId, MOIdentifier mOId, Format format) {
		this.mIId = mIId;
		this.mOId = mOId;
		this.format = format;
	}
	// by Holger
	public MediaInstance(){		
	}

	public MIIdentifier getIdentifier() {
        return mIId;
    }

    public Format getFormat() {
        return format;
    }

    private void setFormat(Format format) {
        this.format = format;
    }

    private Format format;
    private MIIdentifier mIId;
    private MOIdentifier mOId;
	/**
	 * @return
	 */
	public MIIdentifier getMIId() {
		return mIId;
	}

	/**
	 * @return
	 */
	public MOIdentifier getMOId() {
		return mOId;
	}

	/**
	 * @param identifier
	 */
	public void setMIId(MIIdentifier identifier) {
		mIId = identifier;
	}

	/**
	 * @param identifier
	 */
	public void setMOId(MOIdentifier identifier) {
		mOId = identifier;
	}

}
