/* Generated by Together */

package multimonster.common.media;

import java.io.Serializable;
import java.util.Date;


/**
 * contains all content-based metadata for a MediaObject. format-based metadata is stored at Mediainstances. 
 */
public class MetaData  implements Serializable{
    private String title = "";
    private String outline = "";
    private Duration duration = null;
    private Date dateOfRelease = null; 
    private boolean colored = true;
    private int ageRestriction = 0;
    private String language = "";
    private Actor[] actors = null;
    private int numOfFrames = 0;
    
    public MetaData(){
    }
    
	/**
	 * Added for a minimum of metadata-information
	 * 
	 * TODO added by JM
	 */
	public MetaData(String title, String outline) {
		this.title = title;
		this.outline = outline;
	}

    public MetaData(String title, String outline, Duration duration) {
    	this.title = title;
    	this.outline = outline;
    	this.duration = duration;
    }
    
	/**
	 * @return
	 */
	public Actor[] getActors() {
		return actors;
	}

	/**
	 * @return
	 */
	public int getAgeRestriction() {
		return ageRestriction;
	}

	/**
	 * @return
	 */
	public boolean isColored() {
		return colored;
	}

	/**
	 * @return
	 */
	public Date getDateOfRelease() {
		return dateOfRelease;
	}

	/**
	 * @return
	 */
	public Duration getDuration() {
		return duration;
	}

	/**
	 * @return
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * @return
	 */
	public String getOutline() {
		return outline;
	}

	/**
	 * @return
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param actors
	 */
	public void setActors(Actor[] actors) {
		this.actors = actors;
	}

	/**
	 * @param i
	 */
	public void setAgeRestriction(int i) {
		ageRestriction = i;
	}

	/**
	 * @param b
	 */
	public void setColored(boolean b) {
		colored = b;
	}

	/**
	 * @param date
	 */
	public void setDateOfRelease(Date date) {
		dateOfRelease = date;
	}

	/**
	 * @param string
	 */
	public void setDuration(Duration duration) {
		this.duration = duration;
	}

	/**
	 * @param string
	 */
	public void setLanguage(String string) {
		language = string;
	}

	/**
	 * @param string
	 */
	public void setOutline(String string) {
		outline = string;
	}

	/**
	 * @param string
	 */
	public void setTitle(String string) {
		title = string;
	}

	/**
	 * @return Returns the numOfFrames.
	 */
	public int getNumOfFrames() {
		return numOfFrames;
	}

	/**
	 * @param numOfFrames The numOfFrames to set.
	 */
	public void setNumOfFrames(int numOfFrames) {
		this.numOfFrames = numOfFrames;
	}

}
