/* Generated by Together */

package multimonster.common.media;

/**
 * mediaObjects array may be empty; was just wrote down, because it could be useful some day 
 */
public class MOGroup {
    private int groupNumber;
    private MOIdentifier[] mediaObjects;
}
