/* Generated by Together */

package multimonster.usermanager;

import org.apache.log4j.Logger;

import multimonster.common.UserIdentifier;
import multimonster.common.Action;
import multimonster.common.media.MOGroup;
import multimonster.common.media.MOIdentifier;

public class RightsManager {
	
	private static Logger log = Logger.getLogger(RightsManager.class);
	
	public RightsManager() {
	}
	
    public boolean isActionAllowed(UserIdentifier user, MOIdentifier mediaObject, Action action) {
    	log.debug(this.getClass().getName() + ".isActionAllowed() ... sure it is");
    	return true;
    }

    /**
     * gives a usergroup a MORight on a MediaObjectGroup 
     */
    public void grantRight(int usergroup, MOGroup mediaObjectGroup, Action action) {
		log.debug(this.getClass().getName() + ".grantRight()");
    }

    public void revokeRight(int usergroup, MOGroup moGroup, Action newAction) {
		log.debug(this.getClass().getName() + ".revokeRight()");
    }
}
